name: Deploy Portfolio

on:
  push:
    branches:
      - main

env:
  # This removes the warning and opts into the new Node 24 runner
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio
            git pull origin main
            # Using the full path to npm if needed, or ensure NVM is loaded
            npm install
            npm run build